version: '3.8'

services:
  # Service MongoDB
  mongodb:
    image: mongo:6.0
    container_name: nippon-kempo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - nippon-kempo-network

  # Service Mongo Express pour visualiser les données
  mongo-express:
    image: mongo-express:latest
    container_name: nippon-kempo-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - nippon-kempo-network

  # Service Backend Fastify
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nippon-kempo-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://nippon_app:nippon_password@mongodb:27017/nippon-kempo
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - nippon-kempo-network

volumes:
  mongodb_data:

networks:
  nippon-kempo-network:
    driver: bridge